### ISSUE TITLE
No results at all

### ISSUE THREAD

**Issue by maxmstrmn** [LeonDeHill/Self-Driving-Car-Tensorflow#2]
Hi,

am using your code to explore, but unfortunately after training, the steering wheel doesn't turn at all. Also, the trained model .h5 file has a much smaller size on disk than "leon.h5". 
If I print the model summary, it seems there are some layers missing, compared to "leon.h5"?

Please help and give me some advise or information about yout training environment.

Kind regards
max 

Windows 10 with tensorflow-gpu 2.0 and keras 2.3.0
Ubuntu 18.04 with tensorflow 1.14 and keras 2.3.0

**Comment by littlemountainman** [comment]
Hello, 
sorry for the late response. I cant reproduce your issue. I tested everything on Ubuntu 16.04 with TF 1.14.

I am currently testing this version again and try to solve the issue

**Comment by littlemountainman** [comment]
A newer and better version of the code will go online soon.

**Comment by littlemountainman** [comment]
Testing done. I cannot reproduce this error. Is there any error message you can give me ?

**Comment by maxmstrmn** [comment]
Hi,
thanks! There is no error message, it just didn't work.
Will test the new code. Is it compativ´ble with TF 2.0?

**Comment by littlemountainman** [comment]
Yes it should be compatible with the current build

**Comment by maxmstrmn** [comment]
Could you provide your system setup (Hardware, OS and so on) so we can compare? Would be awesome!

**Comment by littlemountainman** [comment]
Ubuntu 16.04, Intel i7 9700k, 64GB of RAM, Single 1080 Ti

**Comment by littlemountainman** [comment]
Also I have a discord. https://discord.gg/nECdb4J

**Comment by maxmstrmn** [comment]
Hi, thank you for this information. I tried the new code but I have issues creating the training files. I downloaded and installed everything, but if I run the reader.py it only creates a bunch of very small (empty) npy files. What can I do?

EDIT: Seems that the script is wrong (e.g. it searches for "rlog.bz2" but in the downloaded folders only "raw_log.bz2" exists... Same for the hevc video.
